In [1]:
import pandas as pd
from scipy import stats

In [2]:
# Step 1: Load the dataset into a DataFrame
df = pd.read_csv('demo.csv')

In [3]:
z_scores = stats.zscore(df)
threshold = 3
outlier_indices = (abs(z_scores) > threshold).any(axis=1)

In [4]:
outlier_indices

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26    False
27    False
28    False
dtype: bool

In [5]:
# Print indices of outlier rows
print("Indices of outlier rows:")
print(df[outlier_indices].index)

Indices of outlier rows:
Index([10, 11, 14, 25], dtype='int64')

In [6]:
df

,math score,reading score,writing score,placement score,placement offer count,club join year
0,80,68,70,89,3,2019
1,71,61,85,91,3,2019
2,79,16,87,77,2,2018
3,61,77,74,76,2,2020
4,78,71,67,90,3,2019
5,73,68,90,80,2,2019
6,77,62,70,35,2,2020
7,74,45,80,12,1,2019
8,76,60,79,77,2,2020
9,75,65,85,87,3,2018
10,160,67,12,83,2,2020
11,79,72,88,180,2,2019
12,80,80,78,94,3,2021
13,78,69,71,90,3,2019
14,75,1,71,81,2,2019
15,78,62,79,93,3,2021
16,86,78,80,88,3,2019
17,80,74,23,76,2,2021
18,75,62,86,87,3,2019
19,82,70,87,94,3,2019
20,69,65,84,35,1,2018
21,100,77,70,91,3,2018
22,72,60,78,94,3,2019
23,74,65,71,84,2,2019
24,75,77,83,77,2,2020
25,180,67,63,75,3,2021
26,72,120,70,84,2,2021
27,71,79,88,85,3,2021
28,120,73,71,94,3,2019

In [7]:
# Step 3: Replace outliers with median values
median_values = df.median()
df[outlier_indices] = median_values

In [8]:
df

,math score,reading score,writing score,placement score,placement offer count,club join year
0,80,68,70,89,3,2019
1,71,61,85,91,3,2019
2,79,16,87,77,2,2018
3,61,77,74,76,2,2020
4,78,71,67,90,3,2019
5,73,68,90,80,2,2019
6,77,62,70,35,2,2020
7,74,45,80,12,1,2019
8,76,60,79,77,2,2020
9,75,65,85,87,3,2018
10,77,68,78,85,3,2019
11,77,68,78,85,3,2019
12,80,80,78,94,3,2021
13,78,69,71,90,3,2019
14,77,68,78,85,3,2019
15,78,62,79,93,3,2021
16,86,78,80,88,3,2019
17,80,74,23,76,2,2021
18,75,62,86,87,3,2019
19,82,70,87,94,3,2019
20,69,65,84,35,1,2018
21,100,77,70,91,3,2018
22,72,60,78,94,3,2019
23,74,65,71,84,2,2019
24,75,77,83,77,2,2020
25,77,68,78,85,3,2019
26,72,120,70,84,2,2021
27,71,79,88,85,3,2021
28,120,73,71,94,3,2019